//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ServicioWebTareas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tareas", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tareas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private System.Nullable<int> IdPersonaField;
        
        private System.Nullable<int> porcentajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                if ((this.porcentajeField.Equals(value) != true)) {
                    this.porcentajeField = value;
                    this.RaisePropertyChanged("porcentaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWebTareas.WSTareasSoap")]
    public interface WSTareasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarTareasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareas", ReplyAction="*")]
        Datos.ServicioWebTareas.MostrarTareasResponse MostrarTareas(Datos.ServicioWebTareas.MostrarTareasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareas", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasResponse> MostrarTareasAsync(Datos.ServicioWebTareas.MostrarTareasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareas", ReplyAction="*")]
        Datos.ServicioWebTareas.BuscarTareasResponse BuscarTareas(Datos.ServicioWebTareas.BuscarTareasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareas", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasResponse> BuscarTareasAsync(Datos.ServicioWebTareas.BuscarTareasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasCompletadas", ReplyAction="*")]
        Datos.ServicioWebTareas.BuscarTareasCompletadasResponse BuscarTareasCompletadas(Datos.ServicioWebTareas.BuscarTareasCompletadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasCompletadas", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasCompletadasResponse> BuscarTareasCompletadasAsync(Datos.ServicioWebTareas.BuscarTareasCompletadasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarTareasCompletadasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasCompletadas", ReplyAction="*")]
        Datos.ServicioWebTareas.MostrarTareasCompletadasResponse MostrarTareasCompletadas(Datos.ServicioWebTareas.MostrarTareasCompletadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasCompletadas", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasCompletadasResponse> MostrarTareasCompletadasAsync(Datos.ServicioWebTareas.MostrarTareasCompletadasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasPendientes", ReplyAction="*")]
        Datos.ServicioWebTareas.BuscarTareasPendientesResponse BuscarTareasPendientes(Datos.ServicioWebTareas.BuscarTareasPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasPendientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasPendientesResponse> BuscarTareasPendientesAsync(Datos.ServicioWebTareas.BuscarTareasPendientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarTareasPendientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasPendientes", ReplyAction="*")]
        Datos.ServicioWebTareas.MostrarTareasPendientesResponse MostrarTareasPendientes(Datos.ServicioWebTareas.MostrarTareasPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasPendientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasPendientesResponse> MostrarTareasPendientesAsync(Datos.ServicioWebTareas.MostrarTareasPendientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasSinComenzar", ReplyAction="*")]
        Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse BuscarTareasSinComenzar(Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTareasSinComenzar", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse> BuscarTareasSinComenzarAsync(Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarTareasSinComenzarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasSinComenzar", ReplyAction="*")]
        Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse MostrarTareasSinComenzar(Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTareasSinComenzar", ReplyAction="*")]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse> MostrarTareasSinComenzarAsync(Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareas", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasRequestBody Body;
        
        public MostrarTareasRequest() {
        }
        
        public MostrarTareasRequest(Datos.ServicioWebTareas.MostrarTareasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarTareasRequestBody {
        
        public MostrarTareasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasResponseBody Body;
        
        public MostrarTareasResponse() {
        }
        
        public MostrarTareasResponse(Datos.ServicioWebTareas.MostrarTareasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasResult;
        
        public MostrarTareasResponseBody() {
        }
        
        public MostrarTareasResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasResult) {
            this.MostrarTareasResult = MostrarTareasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareas", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasRequestBody Body;
        
        public BuscarTareasRequest() {
        }
        
        public BuscarTareasRequest(Datos.ServicioWebTareas.BuscarTareasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        public BuscarTareasRequestBody() {
        }
        
        public BuscarTareasRequestBody(string titulo) {
            this.titulo = titulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasResponseBody Body;
        
        public BuscarTareasResponse() {
        }
        
        public BuscarTareasResponse(Datos.ServicioWebTareas.BuscarTareasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasResult;
        
        public BuscarTareasResponseBody() {
        }
        
        public BuscarTareasResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasResult) {
            this.BuscarTareasResult = BuscarTareasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasCompletadasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasCompletadas", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasCompletadasRequestBody Body;
        
        public BuscarTareasCompletadasRequest() {
        }
        
        public BuscarTareasCompletadasRequest(Datos.ServicioWebTareas.BuscarTareasCompletadasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasCompletadasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public BuscarTareasCompletadasRequestBody() {
        }
        
        public BuscarTareasCompletadasRequestBody(string titulo, int id) {
            this.titulo = titulo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasCompletadasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasCompletadasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasCompletadasResponseBody Body;
        
        public BuscarTareasCompletadasResponse() {
        }
        
        public BuscarTareasCompletadasResponse(Datos.ServicioWebTareas.BuscarTareasCompletadasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasCompletadasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasCompletadasResult;
        
        public BuscarTareasCompletadasResponseBody() {
        }
        
        public BuscarTareasCompletadasResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasCompletadasResult) {
            this.BuscarTareasCompletadasResult = BuscarTareasCompletadasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasCompletadasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasCompletadas", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasCompletadasRequestBody Body;
        
        public MostrarTareasCompletadasRequest() {
        }
        
        public MostrarTareasCompletadasRequest(Datos.ServicioWebTareas.MostrarTareasCompletadasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasCompletadasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MostrarTareasCompletadasRequestBody() {
        }
        
        public MostrarTareasCompletadasRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasCompletadasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasCompletadasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasCompletadasResponseBody Body;
        
        public MostrarTareasCompletadasResponse() {
        }
        
        public MostrarTareasCompletadasResponse(Datos.ServicioWebTareas.MostrarTareasCompletadasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasCompletadasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasCompletadasResult;
        
        public MostrarTareasCompletadasResponseBody() {
        }
        
        public MostrarTareasCompletadasResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasCompletadasResult) {
            this.MostrarTareasCompletadasResult = MostrarTareasCompletadasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasPendientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasPendientes", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasPendientesRequestBody Body;
        
        public BuscarTareasPendientesRequest() {
        }
        
        public BuscarTareasPendientesRequest(Datos.ServicioWebTareas.BuscarTareasPendientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasPendientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public BuscarTareasPendientesRequestBody() {
        }
        
        public BuscarTareasPendientesRequestBody(string titulo, int id) {
            this.titulo = titulo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasPendientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasPendientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasPendientesResponseBody Body;
        
        public BuscarTareasPendientesResponse() {
        }
        
        public BuscarTareasPendientesResponse(Datos.ServicioWebTareas.BuscarTareasPendientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasPendientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasPendientesResult;
        
        public BuscarTareasPendientesResponseBody() {
        }
        
        public BuscarTareasPendientesResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasPendientesResult) {
            this.BuscarTareasPendientesResult = BuscarTareasPendientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasPendientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasPendientes", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasPendientesRequestBody Body;
        
        public MostrarTareasPendientesRequest() {
        }
        
        public MostrarTareasPendientesRequest(Datos.ServicioWebTareas.MostrarTareasPendientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasPendientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MostrarTareasPendientesRequestBody() {
        }
        
        public MostrarTareasPendientesRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasPendientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasPendientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasPendientesResponseBody Body;
        
        public MostrarTareasPendientesResponse() {
        }
        
        public MostrarTareasPendientesResponse(Datos.ServicioWebTareas.MostrarTareasPendientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasPendientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasPendientesResult;
        
        public MostrarTareasPendientesResponseBody() {
        }
        
        public MostrarTareasPendientesResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasPendientesResult) {
            this.MostrarTareasPendientesResult = MostrarTareasPendientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasSinComenzarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasSinComenzar", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasSinComenzarRequestBody Body;
        
        public BuscarTareasSinComenzarRequest() {
        }
        
        public BuscarTareasSinComenzarRequest(Datos.ServicioWebTareas.BuscarTareasSinComenzarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasSinComenzarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public BuscarTareasSinComenzarRequestBody() {
        }
        
        public BuscarTareasSinComenzarRequestBody(string titulo, int id) {
            this.titulo = titulo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarTareasSinComenzarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarTareasSinComenzarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.BuscarTareasSinComenzarResponseBody Body;
        
        public BuscarTareasSinComenzarResponse() {
        }
        
        public BuscarTareasSinComenzarResponse(Datos.ServicioWebTareas.BuscarTareasSinComenzarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarTareasSinComenzarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasSinComenzarResult;
        
        public BuscarTareasSinComenzarResponseBody() {
        }
        
        public BuscarTareasSinComenzarResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasSinComenzarResult) {
            this.BuscarTareasSinComenzarResult = BuscarTareasSinComenzarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasSinComenzarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasSinComenzar", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasSinComenzarRequestBody Body;
        
        public MostrarTareasSinComenzarRequest() {
        }
        
        public MostrarTareasSinComenzarRequest(Datos.ServicioWebTareas.MostrarTareasSinComenzarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasSinComenzarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MostrarTareasSinComenzarRequestBody() {
        }
        
        public MostrarTareasSinComenzarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTareasSinComenzarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTareasSinComenzarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Datos.ServicioWebTareas.MostrarTareasSinComenzarResponseBody Body;
        
        public MostrarTareasSinComenzarResponse() {
        }
        
        public MostrarTareasSinComenzarResponse(Datos.ServicioWebTareas.MostrarTareasSinComenzarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTareasSinComenzarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasSinComenzarResult;
        
        public MostrarTareasSinComenzarResponseBody() {
        }
        
        public MostrarTareasSinComenzarResponseBody(System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasSinComenzarResult) {
            this.MostrarTareasSinComenzarResult = MostrarTareasSinComenzarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTareasSoapChannel : Datos.ServicioWebTareas.WSTareasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTareasSoapClient : System.ServiceModel.ClientBase<Datos.ServicioWebTareas.WSTareasSoap>, Datos.ServicioWebTareas.WSTareasSoap {
        
        public WSTareasSoapClient() {
        }
        
        public WSTareasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTareasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTareasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTareasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.MostrarTareasResponse Datos.ServicioWebTareas.WSTareasSoap.MostrarTareas(Datos.ServicioWebTareas.MostrarTareasRequest request) {
            return base.Channel.MostrarTareas(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareas() {
            Datos.ServicioWebTareas.MostrarTareasRequest inValue = new Datos.ServicioWebTareas.MostrarTareasRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasRequestBody();
            Datos.ServicioWebTareas.MostrarTareasResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareas(inValue);
            return retVal.Body.MostrarTareasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasResponse> Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasAsync(Datos.ServicioWebTareas.MostrarTareasRequest request) {
            return base.Channel.MostrarTareasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasResponse> MostrarTareasAsync() {
            Datos.ServicioWebTareas.MostrarTareasRequest inValue = new Datos.ServicioWebTareas.MostrarTareasRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasRequestBody();
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.BuscarTareasResponse Datos.ServicioWebTareas.WSTareasSoap.BuscarTareas(Datos.ServicioWebTareas.BuscarTareasRequest request) {
            return base.Channel.BuscarTareas(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareas(string titulo) {
            Datos.ServicioWebTareas.BuscarTareasRequest inValue = new Datos.ServicioWebTareas.BuscarTareasRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasRequestBody();
            inValue.Body.titulo = titulo;
            Datos.ServicioWebTareas.BuscarTareasResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareas(inValue);
            return retVal.Body.BuscarTareasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasResponse> Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasAsync(Datos.ServicioWebTareas.BuscarTareasRequest request) {
            return base.Channel.BuscarTareasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasResponse> BuscarTareasAsync(string titulo) {
            Datos.ServicioWebTareas.BuscarTareasRequest inValue = new Datos.ServicioWebTareas.BuscarTareasRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasRequestBody();
            inValue.Body.titulo = titulo;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.BuscarTareasCompletadasResponse Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasCompletadas(Datos.ServicioWebTareas.BuscarTareasCompletadasRequest request) {
            return base.Channel.BuscarTareasCompletadas(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasCompletadas(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasCompletadasRequest inValue = new Datos.ServicioWebTareas.BuscarTareasCompletadasRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasCompletadasRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            Datos.ServicioWebTareas.BuscarTareasCompletadasResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasCompletadas(inValue);
            return retVal.Body.BuscarTareasCompletadasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasCompletadasResponse> Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasCompletadasAsync(Datos.ServicioWebTareas.BuscarTareasCompletadasRequest request) {
            return base.Channel.BuscarTareasCompletadasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasCompletadasResponse> BuscarTareasCompletadasAsync(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasCompletadasRequest inValue = new Datos.ServicioWebTareas.BuscarTareasCompletadasRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasCompletadasRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasCompletadasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.MostrarTareasCompletadasResponse Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasCompletadas(Datos.ServicioWebTareas.MostrarTareasCompletadasRequest request) {
            return base.Channel.MostrarTareasCompletadas(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasCompletadas(int id) {
            Datos.ServicioWebTareas.MostrarTareasCompletadasRequest inValue = new Datos.ServicioWebTareas.MostrarTareasCompletadasRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasCompletadasRequestBody();
            inValue.Body.id = id;
            Datos.ServicioWebTareas.MostrarTareasCompletadasResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasCompletadas(inValue);
            return retVal.Body.MostrarTareasCompletadasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasCompletadasResponse> Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasCompletadasAsync(Datos.ServicioWebTareas.MostrarTareasCompletadasRequest request) {
            return base.Channel.MostrarTareasCompletadasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasCompletadasResponse> MostrarTareasCompletadasAsync(int id) {
            Datos.ServicioWebTareas.MostrarTareasCompletadasRequest inValue = new Datos.ServicioWebTareas.MostrarTareasCompletadasRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasCompletadasRequestBody();
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasCompletadasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.BuscarTareasPendientesResponse Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasPendientes(Datos.ServicioWebTareas.BuscarTareasPendientesRequest request) {
            return base.Channel.BuscarTareasPendientes(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasPendientes(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasPendientesRequest inValue = new Datos.ServicioWebTareas.BuscarTareasPendientesRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasPendientesRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            Datos.ServicioWebTareas.BuscarTareasPendientesResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasPendientes(inValue);
            return retVal.Body.BuscarTareasPendientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasPendientesResponse> Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasPendientesAsync(Datos.ServicioWebTareas.BuscarTareasPendientesRequest request) {
            return base.Channel.BuscarTareasPendientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasPendientesResponse> BuscarTareasPendientesAsync(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasPendientesRequest inValue = new Datos.ServicioWebTareas.BuscarTareasPendientesRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasPendientesRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasPendientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.MostrarTareasPendientesResponse Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasPendientes(Datos.ServicioWebTareas.MostrarTareasPendientesRequest request) {
            return base.Channel.MostrarTareasPendientes(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasPendientes(int id) {
            Datos.ServicioWebTareas.MostrarTareasPendientesRequest inValue = new Datos.ServicioWebTareas.MostrarTareasPendientesRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasPendientesRequestBody();
            inValue.Body.id = id;
            Datos.ServicioWebTareas.MostrarTareasPendientesResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasPendientes(inValue);
            return retVal.Body.MostrarTareasPendientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasPendientesResponse> Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasPendientesAsync(Datos.ServicioWebTareas.MostrarTareasPendientesRequest request) {
            return base.Channel.MostrarTareasPendientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasPendientesResponse> MostrarTareasPendientesAsync(int id) {
            Datos.ServicioWebTareas.MostrarTareasPendientesRequest inValue = new Datos.ServicioWebTareas.MostrarTareasPendientesRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasPendientesRequestBody();
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasPendientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasSinComenzar(Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest request) {
            return base.Channel.BuscarTareasSinComenzar(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> BuscarTareasSinComenzar(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest inValue = new Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasSinComenzarRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasSinComenzar(inValue);
            return retVal.Body.BuscarTareasSinComenzarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse> Datos.ServicioWebTareas.WSTareasSoap.BuscarTareasSinComenzarAsync(Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest request) {
            return base.Channel.BuscarTareasSinComenzarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.BuscarTareasSinComenzarResponse> BuscarTareasSinComenzarAsync(string titulo, int id) {
            Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest inValue = new Datos.ServicioWebTareas.BuscarTareasSinComenzarRequest();
            inValue.Body = new Datos.ServicioWebTareas.BuscarTareasSinComenzarRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).BuscarTareasSinComenzarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasSinComenzar(Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest request) {
            return base.Channel.MostrarTareasSinComenzar(request);
        }
        
        public System.Collections.Generic.List<Datos.ServicioWebTareas.Tareas> MostrarTareasSinComenzar(int id) {
            Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest inValue = new Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasSinComenzarRequestBody();
            inValue.Body.id = id;
            Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse retVal = ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasSinComenzar(inValue);
            return retVal.Body.MostrarTareasSinComenzarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse> Datos.ServicioWebTareas.WSTareasSoap.MostrarTareasSinComenzarAsync(Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest request) {
            return base.Channel.MostrarTareasSinComenzarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Datos.ServicioWebTareas.MostrarTareasSinComenzarResponse> MostrarTareasSinComenzarAsync(int id) {
            Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest inValue = new Datos.ServicioWebTareas.MostrarTareasSinComenzarRequest();
            inValue.Body = new Datos.ServicioWebTareas.MostrarTareasSinComenzarRequestBody();
            inValue.Body.id = id;
            return ((Datos.ServicioWebTareas.WSTareasSoap)(this)).MostrarTareasSinComenzarAsync(inValue);
        }
    }
}
